### ISSUE TITLE
Website suggestions!

### ISSUE THREAD

**Issue by michaelgriffindrake** [rescrv/HyperDex#106]
Here are two simple suggestions for the website that I _heartily_ recommend you implement in order to better the user experience:
- Drive home the fact that the project is open source and publicly hosted on GitHub
  - This will ensure that the visitor knows that the product is produced and maintained by a virant community, and not a cloistered closed source proprietary system
  - As it stands there is no mention of the fact that the project is open source or what license it is covered by
- On your slider bar in the middle of the page you _should definitely_ implement a back button as well as a forward button and stop the animation when people click on them
  - The way your slider is currently set up hurts usability as it forces the user to navigate through all of the slides in order to get back to the previous one
  - The fact that the slider continues to slide once a user has clicked on a button _also_ hurts usability as they have signified their interest in the content, and they don't want to be automatically forced to the next slide when they are trying to assimilate the current information, _especially_ when there is no back button

Hope that helps a bit!

**Comment by dandv** [comment]
Thanks for [adding the Fork me on GitHub ribbon](https://github.com/rescrv/HyperDex/issues/212)! (I didn't realize my issue was a dupe)
