### ISSUE TITLE
`hyperdex_client_put` blocked when there is an error in message header

### ISSUE THREAD

**Issue by derekchiang** [rescrv/HyperDex#127]
When I call `hyperdex_client_put` from a C client, this error message is printed in a daemon's console:

```
W0923 02:24:11.560714 31502 communication.cc:469] dropping message that has a malformed header; here's some hex: 0000000501
```

Now I understand that this means there is some problem with my message.  But the problem is that the client method call (`hyperdex_client_put`) is blocked.  I don't think this is intended, or is it?  I think a more reasonable behaviour would be to return an error message to the client and let the client method call complete with an exception.

As a side note, maybe we could make the error message more informative?  Like specifying exactly what's wrong with the header.

**Comment by rhencke** [comment]
@derekchiang If it makes you feel any better, I messed up the same thing just now, and your message helped me figure it out.  So, thank you! :)
