### ISSUE TITLE
Build fails on arch linux

### ISSUE THREAD

**Issue by arkhamist** [rescrv/HyperDex#169]
I'm trying to compile hyperdex (latest release) on Arch linux. `configure` fails as follows : 

    ... <snipped> ...
    checking json/json.h usability... no
    checking json/json.h presence... no
    checking for json/json.h... no
    configure: error: 
    -------------------------------------------------
    HyperDex relies upon the libjson library.
    Please install libjson to continue.
    -------------------------------------------------

`json-c` is installed on my system.

    % pacman -Ss json-c
    extra/json-c 0.12-2 [installed]
        A JSON implementation in C

However, the output of `pkg-config` is

    % pkg-config --cflags json-c
    -I/usr/include/json-c

Is hyperdex is incompatible with` json-c 0.12`?

**Comment by dahankzter** [comment]
Is this still a viable fix? I can get by with the docker image for the server but since the app is in Go I need the client to work as well.

**Comment by rescrv** [comment]
The latest HyperDex (1.6) does not depend on json-c in any way.  Also, since July, I've moved my main development platform to ArchLinux, so you should have no trouble building the client for Go.
