### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by takaomag** [rescrv/HyperDex#210]
It would be nice if HyperDex supports python3 (bidings/admin).
Is there any plan to support it ?

**Comment by rescrv** [comment]
Python3 is supported in the latest code from git (f79e9a851776a6511753b1d9ee3f88b8d80c6e79).  Pass ``PYTHON=/usr/bin/python3`` to configure to select Python3.  Similarly, ``PYTHON=/usr/bin/python2``, selects Python 2.  When switching between them, a ``make dist-clean`` is necessary before configuring.

**Comment by takaomag** [comment]
Thanks !
