### ISSUE TITLE
C API with document operations and Authorization ?

### ISSUE THREAD

**Issue by liketemple** [rescrv/HyperDex#214]
I found the Python example of Authorization in Chapter 8 of the online Docs, however, I could not find the  C API with Authorization. Is there any C API with Authorization ? 
There is a same question about the document operations which is introduced in Chapter 7.
Any information will help me a lot, thanks.

**Comment by rescrv** [comment]
The C API exposes authorization calls and supports documents, and is the way the Python code supports both.  For documents, pass the document as a JSON c-string and set the type to HYPERDATATYPE_DOCUMENT.  For authorization, pass macaroons with these calls:  https://github.com/rescrv/HyperDex/blob/master/include/hyperdex/client.h#L119-L123
