### ISSUE TITLE
Atomic map ops appear to have relaxed ordering

### ISSUE THREAD

**Issue by AaronFriel** [rescrv/HyperDex#215]
@rescrv: I wanted to ping you on this because I've resumed work on my library for HyperDex, and I've been working on unifying the backend loop implementation.

There's still a bunch of cruft, but I'm seeing weird glitches when doing unit tests against HyperDex locally with a single coordinator and a single daemon. It appears that this sequence of operations doesn't return consistent results:

1. `put` a map attribute on a key
2. atomically modify a map attribute for the key using one of the map atomic ops
3. immediately `get` that key

Sample output from my unit tests:

```
  initial:   fromList [(17,33),(96,0),(175,84),(234,181),(241,-101)]
  operand:   fromList [(96,49),(175,-72),(234,112),(241,-245)]
  output:    fromList [(-245,49),(17,33),(96,0),(175,12),(234,293),(241,-346)]
  expected:  fromList [(17,33),(96,49),(175,12),(234,293),(241,-346)]
```

It's a randomly generated test - it just throws a bunch of data at HyperDex until it gets an unexpected result. Here the "put" sets the map to have values for keys `17, 96, 175, 234, 241`. The operand is applied with a map for keys `96, 175, 234, 241`. In this case, it's an add (the results can be checked quickly by hand to show that the addition worked for all but two of the keys: `96`, and `-245`.)

But there are *six* keys in the final output: `-245` has a value as well. That key, `-245`, may have been set as part of a previous test, as these errors only seem to occur on computer time scales. If I use the Python library or my own library to make a second `get` after, I get the `expected` result.

Is there a relaxed ordering of these operations, am I crazy, or is there a deeper glitch in my own library?

**Comment by AaronFriel** [comment]
Lest one think "Ah, you're aliasing pointers at the beginning and ending of two arrays", here is some more output, showing a different set of errors:

```
  initial:   fromList [(-1457651,-53124),(-1429630,-2226610),(56924,-3413635),(116313,-2323970),(810848,-3094379),(1561988,2869724),(2929291,2800627)]
  operand:   fromList [(116313,-4007453),(1561988,-3575228),(2929291,3704487)]
  output:    fromList [(-1457651,-53124),(-1429630,-2226610),(56924,-3413635),(116313,-2323970),(810848,-3094379),(1561988,-705504),(2929291,2497661)]
  expected:  fromList [(-1457651,-53124),(-1429630,-2226610),(56924,-3413635),(116313,-6331423),(810848,-3094379),(1561988,-705504),(2929291,6505114)]
```

Here, one addition operation applied, but the other two did not?

**Comment by AaronFriel** [comment]
This was due to a garbage collector error, of all things, which in a minute number of cases would reclaim a piece of memory passed to libhyperdex-client, and thereby mangle it.

That is now fixed and the persons responsible for this error have been dealt with.

**Comment by el33th4x0r** [comment]
Hi Aaron,

Great to hear that this was due to the GC environment and not HyperDex.
Thanks for diligently catching, and then resolving it!

- egs
