### ISSUE TITLE
building with clang

### ISSUE THREAD

**Issue by waitman** [rescrv/HyperDex#224]
clang 3.4.1 on FreeBSD 10.2-RELEASE #0 r286666

everything seems to compile with exception of line 571 in admin/hyperspace_builder.cc

```
In file included from admin/hyperspace_builder.cc:36:
In file included from /usr/include/c++/v1/list:178:
/usr/include/c++/v1/algorithm:3213:99: error: no type named 'iterator_category'
      in 'std::__1::iterator_traits<unsigned long>'
  ...__pred, typename iterator_traits<_ForwardIterator>::iterator_category());
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
admin/hyperspace_builder.cc:571:9: note: in instantiation of function template
      specialization 'std::__1::partition<unsigned long,
      std::__1::vector<hyperdex::region, std::__1::allocator<hyperdex::region> >
      *>' requested here
        partition(sp.subspaces[i].attrs.size(), in->partitions, &sp.subs...
        ^
```

I'm researching a solution for this error, but maybe you have a quick fix?
Thanks

**Comment by waitman** [comment]
update,

This problem is happening because "partitions" is already defined in 
/usr/include/c++/v1/algorithm:

```


template <class ForwardIterator, class Predicate>
    ForwardIterator
    partition(ForwardIterator first, ForwardIterator last, Predicate pred);
```

The compiler is apparently getting confused, or maybe partition should be explicitly referenced anyway?

This fixes the problem:
admin/hyperspace_builder.cc

```
569: for (size_t i = 0; i < sp.subspaces.size(); ++i)
570: {
571:	hyperdex::partition(sp.subspaces[i].attrs.size(), in->partitions, &sp.subspaces[i].regions);
572: }

```
Should compile on gcc, etc, would have to test.

**Comment by waitman** [comment]
one more issue - 
daemon/key_state.cc

barfs tons of errors during compile - important ones are
```
hyperdex::key_state::client_response
method is not marked const
std::push_heap invalid operands to binary expression
```

change line 100 , add const to end.
```
// intentionally backwards so the max heap becomes min heap.
    bool operator < (const client_response& rhs) const
```

haven't yet tested the binaries :) but something to consider when building with clang

**Comment by rescrv** [comment]
HyperDex compiles on clang 3.7 on FreeBSD 9.x.  I didn't test 3.4, but I'm open to any patches to make it work on both.
